# Form implementation generated from reading ui file 'gamestart.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow1(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 400)
        MainWindow.setMinimumSize(QtCore.QSize(500, 400))
        MainWindow.setMaximumSize(QtCore.QSize(500, 400))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.directionDisplay = QtWidgets.QLabel(parent=self.centralwidget)
        self.directionDisplay.setGeometry(QtCore.QRect(10, 10, 481, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.directionDisplay.setFont(font)
        self.directionDisplay.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.directionDisplay.setObjectName("directionDisplay")
        self.difficultyLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.difficultyLabel.setGeometry(QtCore.QRect(20, 100, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.difficultyLabel.setFont(font)
        self.difficultyLabel.setObjectName("difficultyLabel")
        self.startingLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.startingLabel.setGeometry(QtCore.QRect(20, 180, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.startingLabel.setFont(font)
        self.startingLabel.setObjectName("startingLabel")
        self.startGameButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.startGameButton.setGeometry(QtCore.QRect(210, 300, 75, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.startGameButton.setFont(font)
        self.startGameButton.setObjectName("startGameButton")
        self.difficultyButton1 = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.difficultyButton1.setGeometry(QtCore.QRect(50, 140, 51, 17))
        self.difficultyButton1.setObjectName("difficultyButton1")
        self.difficultyGroup = QtWidgets.QButtonGroup(MainWindow)
        self.difficultyGroup.setObjectName("difficultyGroup")
        self.difficultyGroup.addButton(self.difficultyButton1)
        self.difficultyButton2 = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.difficultyButton2.setGeometry(QtCore.QRect(120, 140, 71, 17))
        self.difficultyButton2.setObjectName("difficultyButton2")
        self.difficultyGroup.addButton(self.difficultyButton2)
        self.difficultyButton3 = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.difficultyButton3.setGeometry(QtCore.QRect(200, 140, 61, 17))
        self.difficultyButton3.setObjectName("difficultyButton3")
        self.difficultyGroup.addButton(self.difficultyButton3)
        self.difficultyButton4 = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.difficultyButton4.setGeometry(QtCore.QRect(260, 140, 81, 17))
        self.difficultyButton4.setObjectName("difficultyButton4")
        self.difficultyGroup.addButton(self.difficultyButton4)
        self.radioButton = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.radioButton.setGeometry(QtCore.QRect(50, 220, 71, 17))
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.radioButton_2.setGeometry(QtCore.QRect(130, 220, 61, 17))
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_3 = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.radioButton_3.setGeometry(QtCore.QRect(200, 220, 81, 17))
        self.radioButton_3.setObjectName("radioButton_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Tic-Tac-Toe"))
        self.directionDisplay.setText(_translate("MainWindow", "Select Settings"))
        self.difficultyLabel.setText(_translate("MainWindow", "Difficulty?"))
        self.startingLabel.setText(_translate("MainWindow", "Who goes first?"))
        self.startGameButton.setText(_translate("MainWindow", "Start Game"))
        self.difficultyButton1.setText(_translate("MainWindow", "Easy"))
        self.difficultyButton2.setText(_translate("MainWindow", "Medium"))
        self.difficultyButton3.setText(_translate("MainWindow", "Hard"))
        self.difficultyButton4.setText(_translate("MainWindow", "Impossible"))
        self.radioButton.setText(_translate("MainWindow", "Random"))
        self.radioButton_2.setText(_translate("MainWindow", "Human"))
        self.radioButton_3.setText(_translate("MainWindow", "Computer"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
